package emarket.registrazione;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.config.annotation.ViewControllerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

@Configuration
@Controller
public class ClienteController implements WebMvcConfigurer{

  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private ClienteRepository clienteRepository;

  public void addViewControllers(ViewControllerRegistry registry) {
    registry.addViewController("/registrazione").setViewName("registrazione");
  }

  //HTML
  @GetMapping ("/registrazione")
  public String registrazione(Cliente cliente) {
    return "registrazione";
  }


  @PostMapping("/inserimentoCliente")
  public String inserimentoCliente(Cliente cliente) {
    insertCliente(cliente);
    return "redirect:/registrazione";
  }
    
  
  //REST API 
  @PostMapping ("/inserimento_Cliente")
  public @ResponseBody Cliente insertCliente(Cliente cliente) {
    return clienteRepository.save(cliente);
  }
  
}