package emarket.registrazione;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.config.annotation.ViewControllerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;


@Configuration
@Controller
public class ClienteController implements WebMvcConfigurer, GestioneClienteIF{

  @Autowired // This means to get the bean called userRepository
  // Which is auto-generated by Spring, we will use it to handle the data
  private ClienteRepository clienteRepository;

  public void addViewControllers(ViewControllerRegistry registry) {
    registry.addViewController("/registrazione").setViewName("registrazione");
    //registry.addViewController("/visualizzaCliente").setViewName("registrazione");
  }

  //HTML
  @GetMapping ("/registrazione")
  public String registrazione(Cliente cliente) {
    return "registrazione";
  }


  @PostMapping("/inserimentoCliente")
  public String inserimentoCliente(Cliente cliente) {
    insertCl(cliente);
    return "redirect:/registrazione";
  }
    
  
  //REST API 
  @GetMapping ("/visualizza_Cliente")
  public @ResponseBody Iterable<Cliente> getAllCl() {
    return clienteRepository.findAll();
  }
  
  @PostMapping ("/trova_Cliente")
  public @ResponseBody  Cliente getCl(Long id) {
    return clienteRepository.findById(id).orElseThrow(null);
  }

  
  @PostMapping ("/inserimento_Cliente")
  public @ResponseBody Cliente insertCl(Cliente cliente) {
    return clienteRepository.save(cliente);
  }
}